name: 删除workflow，清理工作流
on:
  #定时触发开始编译(把下面两个#去掉开启,时间设置请看定时编译说明)
  schedule:
    - cron: 0 2 1 * *

#分钟字段：0 表示在分钟为 0 的时候执行，即整点。UTC时间
#小时字段：2 表示在小时为 2 的时候执行，即午夜。UTC时间2点，北京时间8点
#日期字段：1 表示在每月的第 1 天执行。
#月份字段：* 是通配符，表示匹配所有月份，即 1 到 12 月都会匹配。
#星期字段：* 同样是通配符，表示匹配一周中的每一天，因为在指定了日期为每月 1 号的情况下，星期几的设置在此处不起实际作用。

  workflow_dispatch:

jobs:
  del_workflow:
    runs-on: Ubuntu-24.04
    name: delete-workflow-runs
    steps:
    
      - name: 删除workflow，清理工作流
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
#数据或操作记录的保留天数
          keep_minimum_runs: 1
#保留运行记录或实例的数量
